### ISSUE TITLE
Unable to Serialize FilePath on Slave Node

### ISSUE THREAD

**Issue by jonathanamartin** [jenkinsci/ibm-ucdeploy-pipeline-plugin#4]
I'm running into the exception below when attempting to use this plugin on a Jenkins slave.  Any ideas?

**OS:** Linux (both master and slave)
**Jenkins Version:** CloudBees Jenkins Enterprise 2.19.4.2-rolling
**Plugin Version:** vibm-ucdeploy-build-steps-2.4.911656

Here's the usage of the plugin in a pipeline script with values changed:
````
stage ('Create UDeploy Component Version') {
    step([
        $class: 'UCDeployPublisher',
        siteName: 'my-udeploy',
        component: [
            $class: 'com.urbancode.jenkins.plugins.ucdeploy.VersionHelper$VersionBlock',
            componentName: 'compname',
            createComponent: [
                $class: 'com.urbancode.jenkins.plugins.ucdeploy.ComponentHelper$CreateComponentBlock',
                componentTemplate: '',
                componentApplication: 'appname'
            ],
            delivery: [
                $class: 'com.urbancode.jenkins.plugins.ucdeploy.DeliveryHelper$Push',
                pushVersion: 'version',
                baseDir: 'target',
                fileIncludePatterns: '*.war',
                fileExcludePatterns: '',
                pushProperties: 'test.property=testvalue',
                pushDescription: 'Test description from Jenkins.'
            ]
        ]
    ])
}
````
Here's the exception:
```
Unable to serialize hudson.FilePath$FileCallableWrapper@3d3705cb
	at hudson.FilePath.act(FilePath.java:1014)
	at hudson.FilePath.act(FilePath.java:996)
	at com.urbancode.jenkins.plugins.ucdeploy.UCDeployPublisher.perform(UCDeployPublisher.java:530)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:59)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:52)
	at hudson.security.ACL.impersonate(ACL.java:221)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Unable to serialize hudson.FilePath$FileCallableWrapper@3d3705cb
	at hudson.remoting.UserRequest.serialize(UserRequest.java:201)
	at hudson.remoting.UserRequest.<init>(UserRequest.java:64)
	at hudson.remoting.Channel.call(Channel.java:795)
	at hudson.FilePath.act(FilePath.java:1007)
	... 12 more
Caused by: java.io.NotSerializableException: com.urbancode.commons.httpcomponentsutil.PreemptiveAuthHttpClient
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at hudson.remoting.UserRequest._serialize(UserRequest.java:190)
	at hudson.remoting.UserRequest.serialize(UserRequest.java:199)
	... 15 more
Finished: FAILURE
```

I've also asked this question [here](https://developer.ibm.com/answers/questions/356119/publish-to-urbancode-deploy-from-a-jenkins-slave-i.html#answer-377196)

**Comment by nhmathis** [comment]
Try specifying an `Alt User`. There is a short comment in the code that would indicate it's required due to some serialization issues: https://github.com/IBM-UrbanCode/ibm-ucdeploy-pipeline-plugin/blob/master/src/main/java/com/urbancode/jenkins/plugins/ucdeploy/UCDeployPublisher.java#L598


```stage ('Create UDeploy Component Version') {
    step([
        $class: 'UCDeployPublisher',
        siteName: 'my-udeploy',
    altUser: [
        $class: 'com.urbancode.jenkins.plugins.ucdeploy.UCDeployPublisher$UserBlock',
        altUsername: 'USERNAME',
        altUsername:  'PASSWORD',
        adminUser: 'false'
    ],
    component: [
            $class: 'com.urbancode.jenkins.plugins.ucdeploy.VersionHelper$VersionBlock',
            componentName: 'compname',
            createComponent: [
                $class: 'com.urbancode.jenkins.plugins.ucdeploy.ComponentHelper$CreateComponentBlock',
                componentTemplate: '',
                componentApplication: 'appname'
            ],
            delivery: [
                $class: 'com.urbancode.jenkins.plugins.ucdeploy.DeliveryHelper$Push',
                pushVersion: 'version',
                baseDir: 'target',
                fileIncludePatterns: '*.war',
                fileExcludePatterns: '',
                pushProperties: 'test.property=testvalue',
                pushDescription: 'Test description from Jenkins.'
            ]
        ]
    ])
}
```

**Comment by jonathanamartin** [comment]
Hmm.. That didn't make a difference:

```
stage ('Create UDeploy Component Version') {
    step([
        $class: 'UCDeployPublisher',
        siteName: 'my-udeploy',
        altUser: [
            $class: 'com.urbancode.jenkins.plugins.ucdeploy.UCDeployPublisher$UserBlock',
            altUsername: 'USERNAME',
            altUsername:  hudson.util.Secret.fromString('PASSWORD'),
            adminUser: false
    ],
        component: [
            $class: 'com.urbancode.jenkins.plugins.ucdeploy.VersionHelper$VersionBlock',
            componentName: 'compname',
            createComponent: [
                $class: 'com.urbancode.jenkins.plugins.ucdeploy.ComponentHelper$CreateComponentBlock',
                componentTemplate: '',
                componentApplication: 'appname'
            ],
            delivery: [
                $class: 'com.urbancode.jenkins.plugins.ucdeploy.DeliveryHelper$Push',
                pushVersion: 'version',
                baseDir: 'target',
                fileIncludePatterns: '*.war',
                fileExcludePatterns: '',
                pushProperties: 'test.property=testvalue',
                pushDescription: 'Test description from Jenkins.'
            ]
        ]
    ])
}
```

Still getting the following exception:
```
java.io.IOException: Unable to serialize hudson.FilePath$FileCallableWrapper@1a2b70d8
	at hudson.FilePath.act(FilePath.java:1014)
	at hudson.FilePath.act(FilePath.java:996)
	at com.urbancode.jenkins.plugins.ucdeploy.UCDeployPublisher.perform(UCDeployPublisher.java:530)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:59)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:52)
	at hudson.security.ACL.impersonate(ACL.java:221)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Unable to serialize hudson.FilePath$FileCallableWrapper@1a2b70d8
	at hudson.remoting.UserRequest.serialize(UserRequest.java:201)
	at hudson.remoting.UserRequest.<init>(UserRequest.java:64)
	at hudson.remoting.Channel.call(Channel.java:795)
	at hudson.FilePath.act(FilePath.java:1007)
	... 12 more
Caused by: java.io.NotSerializableException: com.urbancode.commons.httpcomponentsutil.PreemptiveAuthHttpClient
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at hudson.remoting.UserRequest._serialize(UserRequest.java:190)
	at hudson.remoting.UserRequest.serialize(UserRequest.java:199)
	... 15 more
Finished: FAILURE
```

**Comment by jonathanamartin** [comment]
Is there any other information I can provide that would be helpful?

**Comment by jonathanamartin** [comment]
Or is there a way we can get more detailed logs?

**Comment by jonathanamartin** [comment]
Looks like others are having the same issue with running on slave.
https://developer.ibm.com/answers/questions/15670/jenkins-publish-artifacts-failed.htmlhttps://developer.ibm.com/answers/questions/252514/error-while-publishing-artifacts-from-jenkins-1554.html?smartspace=open_2

**Comment by nhmathis** [comment]
Two specific changes were made since that devAnswers question to resolve serialization issues.
1) https://github.com/IBM-UrbanCode/ibm-ucdeploy-pipeline-plugin/commit/24a7fdb097d93c663ae5b46996eb0f137f6b4021
2) https://github.com/IBM-UrbanCode/ibm-ucdeploy-pipeline-plugin/commit/c76f09db38c9bf33579e8051032bab4a930fb20e


I may have given you incorrect syntax. I would confirm using the `pipeline-syntax` generator tool. 

Through the tool and only specifying the altUser and deploy server information, it generated this...
```
step([$class: 'UCDeployPublisher',
    altUser: [
        adminUser: true,
        altPassword: <object of type hudson.util.Secret>,
        altUsername: 'username'], 
    siteName: 'Docker IBM UrbanCode Deploy Server'])
```

**Comment by jonathanamartin** [comment]
That's the syntax I used previously.  Had to use a `boolean` and `hudson.util.Secret`.  Just tested again with the same exception.  

I tried and admin and non-admin UDeploy user.  Also, this appears to be affecting the plugin's use in Freestyle jobs too.

Could there be a dependent plugin that needs to be updated?  It's hard to tell since we have to manually install it.

**Comment by jonathanamartin** [comment]
I just verified the version we were using with our operations team.  It was 2.2.x.  Upgraded and we're good.  Apologies for the run around.
